server:
  port: 8888
spring:
  application:
    name: seata-multi-datasource
  datasource:
    dynamic:
      primary: order
      strict: true
      seata: true
      datasource:
        order:
          username: fuwu
          password: baie_test_2000
          url: jdbc:mysql://rm-bp1is9caac5z435j0o.mysql.rds.aliyuncs.com:3306/seata_order?useUnicode=false&autoReconnect=true&characterEncoding=utf-8&tcpRcvBuf=2048000&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.cj.jdbc.Driver
          schema: classpath:db/schema-order.sql
        account:
          username: fuwu
          password: baie_test_2000
          url: jdbc:mysql://rm-bp1is9caac5z435j0o.mysql.rds.aliyuncs.com:3306/seata_account?useUnicode=false&autoReconnect=true&characterEncoding=utf-8&tcpRcvBuf=2048000&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.cj.jdbc.Driver
          schema: classpath:db/schema-account.sql
        product:
          username: fuwu
          password: baie_test_2000
          url: jdbc:mysql://rm-bp1is9caac5z435j0o.mysql.rds.aliyuncs.com:3306/seata_product?useUnicode=false&autoReconnect=true&characterEncoding=utf-8&tcpRcvBuf=2048000&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.cj.jdbc.Driver
          schema: classpath:db/schema-product.sql
  cloud:
    alibaba:
      seata:
        tx-service-group: baie_tx_group

seata:
  config:
    type: nacos
    nacos:
      server-addr: 10.10.47.4
      group: SEATA_GROUP
